---
- name: make changes to RHEL 7 os
  hosts: all
  become: true
  tasks:
  - name: Start httpd service
    ansible.builtin.systemd:
      state: started
      name: httpd
    become: true
    become_method: sudo

  - name: remove expiry time
    ansible.builtin.user:
      name: mi31
      expires: -1
    become: true
    become_method: sudo
    
      
