---
- name: make changes to RHEL 7 os
  hosts: all
  become: true
  tasks:
  - name: Start httpd service
    ansible.builtin.systemd:
      state: started
      name: httpd
 

  - name: remove expiry time using chage
    ansible.builtin.shell:
      cmd: chage -M -1 test3
