---
- name: make changes to RHEL 7 os
  hosts: all
  become: true
  tasks:
  - name: Start httpd service
    ansible.builtin.systemd:
      state: started
      name: httpd
 
  - name: Starting at Ansible 2.6, modify user, remove expiry time
    ansible.builtin.user:
      name: test4
      expires: -1

