---
- name: make changes to RHEL 7 os
  hosts: all
  become: true
  tasks:
  - name: Start httpd service
    ansible.builtin.systemd:
      state: started
      name: httpd
 

  - name: remove expiry time
    ansible.builtin.user:
      name: test3
      state: present
      expires: -1

    
      
