---
- name: make changes to RHEL 7 os
  hosts: all
  become: true
  gather_facts: False
  tasks:
  - name: Start httpd service
    ansible.builtin.systemd:
      state: started
      name: httpd
 
  - name: remove password expiry time using chage
    ansible.builtin.shell:
      cmd: chage -M -1 test4

